# Generated by Django 4.2.6 on 2023-10-24 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='friends_ids',
            field=models.ManyToManyField(blank=True, related_name='user_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='friends_number',
            field=models.IntegerField(default=2),
        ),
    ]
