# Generated by Django 4.2.6 on 2023-10-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('image', models.ImageField(default='media/default_image.jpeg', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
